# Hierarchical distance sampling for Duke Farms

# Load data and libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(lubridate)

# see distance data structure from AHM1_08.05.R section 8.5.4

# read in cleaned 2024 data
d <- read_xlsx("data/Datasheet2024_cleaned.xlsx", sheet = "dukebirds2024") %>%
  mutate(pt = case_when(point %in% 1:9 ~ paste0("DUKE_0", point),
                        !point %in% 1:9 ~ paste0("DUKE_", point)),
         year = "Y24",
         time = hour(start) + minute(start)/60,
         dist = case_when(is.na(distance) ~ 59, # mean; would be better to impute random, 
                                                  # but this affects no BOBO
                          TRUE ~ distance),
         pt = paste0(year, pt))
table(d$pt)

# read in and combine 2018-2019 data
survey.pt.lookup <- data.frame(pt = c("DUKE_01", "DUKE_01", 
                                      "DUKE_02", "DUKE_02",
                                      "DUKE_03", "DUKE_03",
                                      "DUKE_04", "DUKE_04",
                                      "DUKE_05", "DUKE_05",
                                      "DUKE_06", "DUKE_06",
                                      "DUKE_07", "DUKE_07",
                                      "DUKE_08", "DUKE_08",
                                      "DUKE_09", "DUKE_09",
                                      "DUKE_10", "DUKE_10",
                                      "DUKE_11", "DUKE_11",
                                      "DUKE_12", "DUKE_12",
                                      "DUKE_13", "DUKE_13",
                                      "DUKE_19", "DUKE_19",
                                      "DUKE_20", "DUKE_20",
                                      "DUKE_21", "DUKE_21",
                                      "DUKE_24", "DUKE_24",
                                      "DUKE_25", "DUKE_25",
                                      "DUKE_26", "DUKE_26"
                  ),
           pt18 = c("SR06", "SY04", 
                    "SR24", "SY30",
                    "SR19", "SY25",
                    "SY46", "SR43",
                    "SY41", "SR36",
                    "SR57", "SY56",
                    "KY36", "KR40",
                    "KY31", "KR35",
                    "KR50", "KY49",
                    "KY23", "KR26",
                    "KY17", "KR15",
                    "KY05", "KR03",
                    "KY08", "KR10",
                    "KY42", "KR44",
                    "KY25", "KR28",
                    "KY47", "KR33",
                    "SR08", "SY11",
                    "SR22", "SY27",
                    "SY44", "SR46")
                    )  

u <- read.csv("data/dukebirds2018-2019.QCed.2019-11-20.csv") %>%
  rename(pt18 = pt) 

u.fin <- u %>%
  left_join(survey.pt.lookup, by = join_by(pt18)) %>%
  filter(!is.na(pt),
         per %in% 3:8) %>%
  mutate(time = hour(hm(start)) + minute(hm(start))/60,
         date = mdy(date), 
         year = case_when(year(date) %in% 2018 ~ "Y18",
                       year(date) %in% 2019 ~ "Y19"),
         pt = paste0(year, pt)) %>%
  rename(species = sp, observer = obs) %>%
  mutate(period = case_when(month(date) %in% 5 ~ 1,
                            month(date) %in% 6 & day(date) < 16 ~ 2,
                            month(date) %in% 6 & day(date) > 15 ~ 3,
                            month(date) %in% 7 & day(date) < 2 ~ 3,
                            month(date) %in% 7 & day(date) > 1 ~ 4,
                            TRUE ~ NA),
         field = substr(pt18, 1,1),
         obsperpt = paste0(observer, period, pt),
         perpt = paste0(period, pt)) %>%
  select(observer, year, date, time, pt, field, 
         period, obsperpt, perpt, species, num, dist)

table(u.fin$pt, u.fin$period) # 6 surveys per point 

sort(unique(u.fin$pt))


# read in and combine 2010, 2012, and 2013 data
# read in 2010-2013 data
k <- read_xlsx("data/Duke Data 2013.xlsx", sheet = "duke3years") %>%
  filter(!PointId %in% c("DUKE_27", "DUKE_28", "DUKE_29",
                         "DUKE_30", "DUKE_31", "DUKE_16",
                         "DUKE_18", "DUKE_22", "DUKE_23",
                         "DUKE_14", "DUKE_15", "DUKE_17")) %>%
  mutate(period = case_when(month(VisitDate) %in% 5 ~ 1,
                            month(VisitDate) %in% 6 & day(VisitDate) < 16 ~ 2,
                            month(VisitDate) %in% 6 & day(VisitDate) > 15 ~ 3,
                            month(VisitDate) %in% 7 & day(VisitDate) < 2 ~ 3,
                            month(VisitDate) %in% 7 & day(VisitDate) > 1 ~ 4,
                            TRUE ~ NA),
         observer = case_when(UserId %in% "MikeA" ~ "Mike Allen",
                              UserId %in% "kristin" ~ "Kristin M",
                              UserId %in% "laurastern" ~ "Laura Stern",
                              TRUE ~ NA),
         field = case_when(PointId %in% c("DUKE_01", "DUKE_02", "DUKE_03",
                                          "DUKE_04", "DUKE_05", "DUKE_06",
                                          "DUKE_24", "DUKE_25", "DUKE_26") ~ "S",
                           TRUE ~ "K"),
         sp = case_when(sp %in% "Bobolink" ~ "BOBO",
                        sp %in% "Grasshopper Sparrow" ~ "GRSP",
                        sp %in% "Eastern Meadowlark" ~ "EAME",
                        sp %in% "Red-winged Blackbird" ~ "RWBL",
                        sp %in% "American Kestrel" ~ "AMKE",
                        TRUE ~ "Other"),
         time = as.numeric(substr(VisitTime, 1,1)) + 
           as.numeric(substr(VisitTime, 2,3))/60) %>%
  mutate(pt = paste0(year, PointId)) %>%
  mutate(obsperpt = paste0(observer, period, pt),
         perpt = paste0(period, pt)) %>%
  select(observer, year, date = VisitDate, time, pt, field, period, 
         obsperpt, perpt, species = sp, num = n, distcat = dist)

######
### make version of data for Hierarchical Distance Sampling modeling
######

# get info for all points surveyed in 2024
d.allpts <- d %>%
  select(period, pt, observer, field, year, date, time) %>%
  distinct() %>%
  arrange(pt, year, period) %>%
  mutate(perpt = paste0(period, pt)) %>%
  mutate(dup = duplicated(perpt)*1)
table(d.allpts$pt, d.allpts$period)

# get info for all points surveyed in 2018 and 2019 (subset that matches 2024 set)
u.allpts <- u.fin %>%
  select(period, pt, observer, field, year, date, time) %>%
  distinct() %>%
  arrange(pt, year, period) %>%
  mutate(obsperpt = paste0(observer, period, pt),
         perpt = paste0(period, pt)) %>%
  mutate(dup = duplicated(perpt)*1) %>%
  filter(dup %in% 0)
table(u.allpts$pt, u.allpts$period)

# get info for all points surveyed in 2010, 2012 and 2013
k.allpts <- k %>%
  select(period, pt, observer, field, year, date, time) %>%
  distinct() %>%
  arrange(pt, year, period) %>%
  mutate(obsperpt = paste0(observer, period, pt),
         perpt = paste0(period, pt)) %>%
  mutate(dup = duplicated(perpt)*1) %>%
  filter(dup %in% 0)
table(k.allpts$pt, k.allpts$period)

# combine for for all points surveyed in 2018, 2019, and 2024
allpts <- d.allpts %>%
  bind_rows(select(u.allpts, -obsperpt)) %>%
  bind_rows(select(k.allpts, -obsperpt)) %>%
  arrange(pt, period)
  
# subset just BOBO observations (2024)
d.b <- d %>%
  filter(species %in% "BOBO",
         dist < 101) %>%
  select(year, pt, field, period, time, observer, num, dist)

# subset just BOBO observations (2018 - 2019)
u.b <- u.fin %>%
  filter(species %in% "BOBO",
         obsperpt %in% u.allpts$obsperpt,
         dist < 101) %>%
  select(year, pt, field, period, time, observer, num, dist)

# get vector of all distance measurements & impute random distances into 2010-2013 data
all.b.dist <- c(d.b$dist, u.b$dist)[c(d.b$dist, u.b$dist)<100]
hist(all.b.dist)
nrow(k) # 952
k$dist <- sample(all.b.dist, size = nrow(k), replace = T)
k$dist2 <- sample(all.b.dist, size = nrow(k), replace = T)
k$dist3 <- sample(all.b.dist, size = nrow(k), replace = T)
k$dist4 <- sample(all.b.dist, size = nrow(k), replace = T)
k$dist5 <- sample(all.b.dist, size = nrow(k), replace = T)

# subset just BOBO observations (2010, 2012, 2013)
k.b <- k %>%
  filter(species %in% "BOBO",
         obsperpt %in% k.allpts$obsperpt,
         !distcat %in% "Greater than 100 m") %>%
  select(year, pt, field, period, time, observer, num,
         dist, dist2, dist3, dist4, dist5)

###
### find out which points had no BOBO (2024)
###
length(unique(d$pt))
length(unique(d.b$pt))
(d.b.missing <- d.allpts %>%
  filter(!pt %in% unique(d.b$pt)) %>%
  select(pt) %>%
  distinct())

# add the missing points back into the BOBO observation file
d.b <- d %>%
  filter(species %in% "BOBO",
         dist < 101) %>%
  select(field, year, pt, dist, num) %>%
  bind_rows(d.allpts %>% filter(pt %in% d.b.missing$pt) %>% 
              select(field, year, pt) %>% distinct()) %>%
  arrange(pt) %>%
  mutate(ptn = as.numeric(as.factor(pt)),
         dist.na = ifelse(is.na(dist), NA, 1),
         fld = as.numeric(as.factor(field))-1)

# number of observations that have 2,3,4,5 individuals (none had >5)
d.b2 <- d.b %>% filter(num %in% 2)
d.b3 <- d.b %>% filter(num %in% 3)
d.b4 <- d.b %>% filter(num %in% 4)
d.b5 <- d.b %>% filter(num %in% 5)

# bind additional individuals to the d.b data.frame
  # this makes it so every row = 1 individual
d.b <- d.b %>%
  bind_rows(d.b2) %>%
  bind_rows(d.b3) %>%
  bind_rows(d.b3) %>%
  bind_rows(d.b4) %>%
  bind_rows(d.b4) %>%
  bind_rows(d.b4) %>%
  bind_rows(d.b5) %>%
  bind_rows(d.b5) %>%
  bind_rows(d.b5) %>%
  bind_rows(d.b5) %>%
  mutate(num = 1) %>%
  select(-num)
hist(d.b$dist, nclass = 20)

# find out which points had no BOBO (2018-2019)
length(unique(u.fin$pt)) # 38
length(unique(u.b$pt)) # 35
(u.b.missing <- u.allpts %>%
  filter(!pt %in% unique(u.b$pt)) %>%
  select(pt) %>%
  distinct())

# add the missing points back into the BOBO observation file
u.b <- u.fin %>%
  filter(species %in% "BOBO",
         obsperpt %in% u.allpts$obsperpt, # keeps just the four surveys, 1 for each period
         dist < 101) %>%
  select(field, year, pt, dist, num) %>%
  bind_rows(u.allpts %>% filter(pt %in% u.b.missing$pt) %>% 
              select(field, year, pt) %>% distinct()) %>%
  arrange(pt) %>%
  mutate(ptn = as.numeric(as.factor(pt)),
         dist.na = ifelse(is.na(dist), NA, 1),
         fld = as.numeric(as.factor(field))-1)

# number of observations that have 2,3,4,5,6,8,9,10,11 individuals (none had 7 or >11)
u.b2 <- u.b %>% filter(num %in% 2)
u.b3 <- u.b %>% filter(num %in% 3)
u.b4 <- u.b %>% filter(num %in% 4)
u.b5 <- u.b %>% filter(num %in% 5)
u.b6 <- u.b %>% filter(num %in% 6)
u.b8 <- u.b %>% filter(num %in% 8)
u.b9 <- u.b %>% filter(num %in% 9)
u.b10 <- u.b %>% filter(num %in% 10)
u.b11 <- u.b %>% filter(num %in% 11)

# bind additional individuals to the d.b data.frame
  # this makes it so every row = 1 individual
u.b <- u.b %>%
  bind_rows(u.b2) %>%
  bind_rows(u.b3) %>%
  bind_rows(u.b3) %>%
  bind_rows(u.b4) %>%
  bind_rows(u.b4) %>%
  bind_rows(u.b4) %>%
  bind_rows(u.b5) %>%
  bind_rows(u.b5) %>%
  bind_rows(u.b5) %>%
  bind_rows(u.b5) %>%
  bind_rows(u.b6) %>%
  bind_rows(u.b6) %>%
  bind_rows(u.b6) %>%
  bind_rows(u.b6) %>%
  bind_rows(u.b6) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b8) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b9) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b10) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  bind_rows(u.b11) %>%
  mutate(num = 1) %>%
  select(-num)

hist(u.b$dist, nclass = 20)

# find out which points had no BOBO (2010, 2012,2013)
length(unique(k$pt)) # 57
length(unique(k.b$pt)) # 49
(k.b.missing <- k.allpts %>%
  filter(!pt %in% unique(k.b$pt)) %>%
  select(pt) %>%
  distinct())

# add the missing points back into the BOBO observation file
k.b <- k %>%
  filter(species %in% "BOBO",
         obsperpt %in% k.allpts$obsperpt, # keeps just the four surveys, 1 for each period
         !distcat %in% "Greater than 100 m") %>%
  select(field, year, pt, dist, dist2, dist3, dist4, dist5, num) %>%
  bind_rows(k.allpts %>% filter(pt %in% k.b.missing$pt) %>% 
              select(field, year, pt) %>% distinct()) %>%
  arrange(pt) %>%
  mutate(ptn = as.numeric(as.factor(pt)),
         dist.na = ifelse(is.na(dist), NA, 1),
         fld = as.numeric(as.factor(field))-1)
unique(k.b$pt)

# number of observations that have 2,3 or 4 individuals (none had >4)
sort(unique(k.b$num))
k.b2 <- k.b %>% filter(num %in% 2)
k.b3 <- k.b %>% filter(num %in% 3)
k.b4 <- k.b %>% filter(num %in% 4)
k.b5 <- k.b %>% filter(num %in% 5)
k.b6 <- k.b %>% filter(num %in% 6)
k.b7 <- k.b %>% filter(num %in% 7)
k.b9 <- k.b %>% filter(num %in% 9)
k.b25 <- k.b %>% filter(num %in% 25)
k.b55 <- k.b %>% filter(num %in% 55)

# bind additional individuals to the d.b data.frame
  # this makes it so every row = 1 individual
k.b <- k.b %>%
  bind_rows(k.b2) %>%
  bind_rows(k.b3) %>%
  bind_rows(k.b3) %>%
  bind_rows(k.b4) %>%
  bind_rows(k.b4) %>%
  bind_rows(k.b4) %>%
  bind_rows(k.b5) %>%
  bind_rows(k.b5) %>%
  bind_rows(k.b5) %>%
  bind_rows(k.b5) %>%
  bind_rows(k.b6) %>%
  bind_rows(k.b6) %>%
  bind_rows(k.b6) %>%
  bind_rows(k.b6) %>%
  bind_rows(k.b6) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b7) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b9) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b25) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  bind_rows(k.b55) %>%
  mutate(num = 1)

hist(k.b$dist, nclass = 20)

# make 5 versions of k.b dataset
k.b.1 <- k.b %>% select(-dist2, -dist3, -dist4, -dist5)
k.b.2 <- k.b %>% select(-dist, -dist3, -dist4, -dist5) %>% rename(dist = dist2)
k.b.3 <- k.b %>% select(-dist, -dist2, -dist4, -dist5) %>% rename(dist = dist3)
k.b.4 <- k.b %>% select(-dist, -dist2, -dist3, -dist5) %>% rename(dist = dist4)
k.b.5 <- k.b %>% select(-dist, -dist2, -dist3, -dist4) %>% rename(dist = dist5)

# combine just BOBO observations (2018, 2019, and 2024)
b <- d.b %>%
  bind_rows(u.b) %>%
  bind_rows(k.b.1) %>%
  arrange(pt) %>%
  mutate(ptn = as.numeric(as.factor(pt)))
unique(b$pt)
hist(b$dist)

# make field covariate (1 row for each site; 1 = skeet, 0 = kaufman)
(site.covs <- b %>%
  select(ptn, year, field) %>%
  distinct() %>%
  mutate(fld = as.numeric(as.factor(field))-1,
         Y10 = as.numeric(ifelse(year %in% "Y10", 1, 0)),
         Y12 = as.numeric(ifelse(year %in% "Y12", 1, 0)),
         Y13 = as.numeric(ifelse(year %in% "Y13", 1, 0)),
         Y19 = as.numeric(ifelse(year %in% "Y19", 1, 0)),
         Y24 = as.numeric(ifelse(year %in% "Y24", 1, 0))))

# make year covariates (1 row for each site)

# Prepare data (BOBO)
# Number of individuals detected per site
ncap <- table(b$ptn)            # ncap = 1 if no individuals captured
sites0 <- b[is.na(b[,"dist.na"]),]$ptn # sites where nothing was seen
ncap[as.character(sites0)] <- 0    # Fill in 0 for sites with no detections
ncap <- as.vector(ncap)            # Number of individuals detected per site
B <- 103 # max radius distance

# Other data
site <- b[!is.na(b$dist.na),]$ptn   # Site ID of each observation
delta <-  5                       # Distance bin width for rect. approx.
midpt <- seq(delta/2, B, delta)    # Make mid-points and chop up data
dclass <- b$dist %/% delta + 1   # Convert distance to distance category
nD <- length(midpt)               # Number of distance intervals
dclass <- dclass[!is.na(b[,"dist.na"])] # Observed categorical observations
nind <- length(dclass)             # Total number of individuals detected
nsites <- length(unique(site)) + length(unique(sites0))

# Bundle and summarize data set
str( b.jags.data <- list(nsites=nsites, nind=nind, B=B, nD=nD, midpt=midpt,
    delta=delta, ncap=ncap, field=site.covs$fld, Y19 = site.covs$Y19, 
    Y10 = site.covs$Y10, Y12 = site.covs$Y12, Y13 = site.covs$Y13, 
    Y24 = site.covs$Y24, dclass=dclass, site=site) )
```

# Run model
```{r}

# BUGS model specification for point transect data
cat("
model{
  # Priors
  alpha0 ~ dunif(-5,5)
  alpha1 ~ dunif(-5,5)
  alpha2 ~ dunif(-5,5)
  alpha3 ~ dunif(-5,5)
  alpha4 ~ dunif(-5,5)
  alpha5 ~ dunif(-5,5)
  beta0 ~ dunif(-5,5)
  beta1 ~ dunif(-5,5) # field covariate
  beta2 ~ dunif(-5,5) # Y10 covariate
  beta3 ~ dunif(-5,5) # Y12 covariate
  beta4 ~ dunif(-5,5) # Y13 covariate
  beta5 ~ dunif(-5,5) # Y19 covariate
  beta6 ~ dunif(-5,5) # Y24 covariate
  beta7 ~ dunif(-5,5) # interaction covariate
  beta8 ~ dunif(-5,5) # interaction covariate
  beta9 ~ dunif(-5,5) # interaction covariate
  beta10 ~ dunif(-5,5) # interaction covariate
  beta11 ~ dunif(-5,5) # interaction covariate

  for(i in 1:nind){
    dclass[i] ~ dcat(fc[site[i],]) # Part 1 of HM
  }
  for(s in 1:nsites){
    # Construct cell probabilities for nD distance bands
    for(g in 1:nD){                # midpt = mid-point of each band
      log(p[s,g]) <- -midpt[g] * midpt[g] / (2 * sigma[s] * sigma[s])
      pi[s,g] <- ((2 * midpt[g] ) / (B * B)) * delta # prob. per interval
      f[s,g] <- p[s,g] * pi[s,g]
      fc[s,g] <- f[s,g] / pcap[s]
    }
    pcap[s] <- sum(f[s,])           # Pr(capture): sum of rectangular areas

    ncap[s] ~ dbin(pcap[s], N[s])   # Part 2 of HM
    N[s] ~ dpois(lambda[s])         # Part 3 of HM
    log(lambda[s]) <- beta0 + beta1 * field[s] + 
        beta2 * Y10[s] + beta3 * Y12[s] +
        beta4 * Y13[s] + beta5 * Y19[s] + 
        beta6 * Y24[s] + 
        beta7 * field[s] * Y10[s] +
        beta8 * field[s] * Y12[s] +
        beta9 * field[s] * Y13[s] +
        beta10 * field[s] * Y19[s] +
        beta11 * field[s] * Y24[s] # linear model abundance
    log(sigma[s]) <- alpha0 + alpha1 * Y10[s] + alpha2 * Y12[s] +
                      alpha3 * Y13[s] + alpha4 * Y19[s] +
                        alpha5 * Y24[s] # linear model detection
  }

  # Derived parameters
  lam.S.Y18 <- exp(beta0 + beta1)/4
  lam.K.Y18 <- exp(beta0)/4
  lam.S.Y10 <- exp(beta0 + beta1 + beta2 + beta7)/4
  lam.K.Y10 <- exp(beta0 + beta2)/4
  lam.S.Y12 <- exp(beta0 + beta1 + beta3 + beta8)/4
  lam.K.Y12 <- exp(beta0 + beta3)/4
  lam.S.Y13 <- exp(beta0 + beta1 + beta4 + beta9)/4
  lam.K.Y13 <- exp(beta0 + beta4)/4
  lam.S.Y19 <- exp(beta0 + beta1 + beta5 + beta10)/4
  lam.K.Y19 <- exp(beta0 + beta5)/4
  lam.S.Y24 <- exp(beta0 + beta1 + beta6 + beta11)/4
  lam.K.Y24 <- exp(beta0 + beta6)/4
  area.S <- 3.141*100*100/10000 # converted to ha [using 100 m as B was set to 103]
  area.K <- 3.141*100*100/10000 # converted to ha [using 100 m as B was set to 103]
  D.S.Y10 <- (lam.S.Y10)/area.S # mean per sampling period per ha
  D.K.Y10 <- (lam.K.Y10)/area.K # mean per sampling period per ha  
  D.S.Y12 <- (lam.S.Y12)/area.S # mean per sampling period per ha
  D.K.Y12 <- (lam.K.Y12)/area.K # mean per sampling period per ha  
  D.S.Y13 <- (lam.S.Y13)/area.S # mean per sampling period per ha
  D.K.Y13 <- (lam.K.Y13)/area.K # mean per sampling period per ha  
  D.S.Y18 <- (lam.S.Y18)/area.S # mean per sampling period per ha
  D.K.Y18 <- (lam.K.Y18)/area.K # mean per sampling period per ha  
  D.S.Y19 <- (lam.S.Y19)/area.S # mean per sampling period per ha
  D.K.Y19 <- (lam.K.Y19)/area.K # mean per sampling period per ha  
  D.S.Y24 <- (lam.S.Y24)/area.S # mean per sampling period per ha
  D.K.Y24 <- (lam.K.Y24)/area.K # mean per sampling period per ha
  sigma10 <- sigma[1]
  sigma12 <- sigma[20]
  sigma13 <- sigma[38]
  sigma18 <- sigma[57]
  sigma19 <- sigma[76]
  sigma24 <- sigma[95]
}
",fill=TRUE, file="scripts/distance.N.field.6year.int.p.6year.txt")


# Inits
Nst <- ncap + 1
inits.fun <- function(){list(alpha0=3.8, alpha1=0, alpha2=0,
                             beta0=1.8, beta1=0.5, beta2 = 1, beta3 = .8, 
                             beta4 = 0, beta5 = -1, beta6 = 0,
                             beta7 = -.6, beta8 = 0, beta9 = 0.5,
                             beta10 = 0, beta11 = 0, N=Nst)}

# Params to save
params <- c("alpha0", "alpha1", "alpha2",
            "alpha3", "alpha4", "alpha5",
            "beta0", "beta1",
            "beta2", "beta3", 
            "beta4", "beta5",
            "beta6", "beta7",
            "beta8", "beta9",
            "beta10", "beta11",
            "D.S.Y10", "D.K.Y10", 
            "D.S.Y12", "D.K.Y12", 
            "D.S.Y13", "D.K.Y13",            
            "D.S.Y18", "D.K.Y18", 
            "D.S.Y19", "D.K.Y19", 
            "D.S.Y24", "D.K.Y24",
            "lam.S.Y10", "lam.K.Y10",
            "lam.S.Y12", "lam.K.Y12",
            "lam.S.Y13", "lam.K.Y13",
            "lam.S.Y18", "lam.K.Y18",
            "lam.S.Y19", "lam.K.Y19",
            "lam.S.Y24", "lam.K.Y24",
            "sigma10", "sigma12", "sigma13",
            "sigma18", "sigma19", "sigma24") 

# MCMC settings
ni <- 90000   ;   nb <- 0   ; na <- 30000;   nt <- 30   ;   nc <- 3

# Run BUGS (ART 2.3 min) and summarize posteriors
out <- jagsUI::jags(data = b.jags.data, 
                    inits = inits.fun, 
                    parameters.to.save = params, 
                    model.file = "scripts/distance.N.field.6year.int.p.6year.txt",
   n.thin=nt, n.chains=nc, n.burnin=nb, n.iter=ni,
   n.adapt = na,
   n.cores = 3)
# sink("output/b.6years.model.int.p.year.txt")
print(out, 2)
# sink()
# jagsUI:: traceplot(out)
# saveRDS(out, "output/b.6years.int.model.p.year.rds")

```
# plot BOBO
```{r}
out <- readRDS("output/b.6years.int.model.p.year.rds")

# format data for plotting
b.plot <- data.frame(field = rep(c("S", "K"), 6),
           year = c(2010, 2010, 2012, 2012, 2013, 2013, 
                    2018, 2018, 2019, 2019, 2024, 2024),
           Nmed = c(median(out$sims.list$lam.S.Y10), median(out$sims.list$lam.K.Y10), 
                    median(out$sims.list$lam.S.Y12), median(out$sims.list$lam.K.Y12), 
                    median(out$sims.list$lam.S.Y13), median(out$sims.list$lam.K.Y13),
                    median(out$sims.list$lam.S.Y18), median(out$sims.list$lam.K.Y18), 
                    median(out$sims.list$lam.S.Y19), median(out$sims.list$lam.K.Y19), 
                    median(out$sims.list$lam.S.Y24), median(out$sims.list$lam.K.Y24)),
           Nq2.5 = c(quantile(out$sims.list$lam.S.Y10, 0.025), 
                     quantile(out$sims.list$lam.K.Y10, 0.025), 
                    quantile(out$sims.list$lam.S.Y12, 0.025), 
                    quantile(out$sims.list$lam.K.Y12, 0.025), 
                    quantile(out$sims.list$lam.S.Y13, 0.025), 
                    quantile(out$sims.list$lam.K.Y13, 0.025),
                    quantile(out$sims.list$lam.S.Y18, 0.025), 
                    quantile(out$sims.list$lam.K.Y18, 0.025), 
                    quantile(out$sims.list$lam.S.Y19, 0.025), 
                    quantile(out$sims.list$lam.K.Y19, 0.025), 
                    quantile(out$sims.list$lam.S.Y24, 0.025), 
                    quantile(out$sims.list$lam.K.Y24, 0.025)),
           Nq97.5 = c(quantile(out$sims.list$lam.S.Y10, 0.975), 
                     quantile(out$sims.list$lam.K.Y10, 0.975), 
                    quantile(out$sims.list$lam.S.Y12, 0.975), 
                    quantile(out$sims.list$lam.K.Y12, 0.975), 
                    quantile(out$sims.list$lam.S.Y13, 0.975), 
                    quantile(out$sims.list$lam.K.Y13, 0.975),
                    quantile(out$sims.list$lam.S.Y18, 0.975), 
                     quantile(out$sims.list$lam.K.Y18, 0.975), 
                    quantile(out$sims.list$lam.S.Y19, 0.975), 
                    quantile(out$sims.list$lam.K.Y19, 0.975), 
                    quantile(out$sims.list$lam.S.Y24, 0.975), 
                    quantile(out$sims.list$lam.K.Y24, 0.975)),           
           Nq10 = c(quantile(out$sims.list$lam.S.Y10, 0.1), 
                     quantile(out$sims.list$lam.K.Y10, 0.1), 
                    quantile(out$sims.list$lam.S.Y12, 0.1), 
                    quantile(out$sims.list$lam.K.Y12, 0.1), 
                    quantile(out$sims.list$lam.S.Y13, 0.1), 
                    quantile(out$sims.list$lam.K.Y13, 0.1),
                    quantile(out$sims.list$lam.S.Y18, 0.1), 
                     quantile(out$sims.list$lam.K.Y18, 0.1), 
                    quantile(out$sims.list$lam.S.Y19, 0.1), 
                    quantile(out$sims.list$lam.K.Y19, 0.1), 
                    quantile(out$sims.list$lam.S.Y24, 0.1), 
                    quantile(out$sims.list$lam.K.Y24, 0.1)),
           Nq90 = c(quantile(out$sims.list$lam.S.Y10, 0.9), 
                     quantile(out$sims.list$lam.K.Y10, 0.9), 
                    quantile(out$sims.list$lam.S.Y12, 0.9), 
                    quantile(out$sims.list$lam.K.Y12, 0.9), 
                    quantile(out$sims.list$lam.S.Y13, 0.9), 
                    quantile(out$sims.list$lam.K.Y13, 0.9),
                    quantile(out$sims.list$lam.S.Y18, 0.9), 
                     quantile(out$sims.list$lam.K.Y18, 0.9), 
                    quantile(out$sims.list$lam.S.Y19, 0.9), 
                    quantile(out$sims.list$lam.K.Y19, 0.9), 
                    quantile(out$sims.list$lam.S.Y24, 0.9), 
                    quantile(out$sims.list$lam.K.Y24, 0.9))) %>%
  mutate(Dmed = Nmed/pi,
         Dq2.5 = Nq2.5/pi,
         Dq97.5 = Nq97.5/pi,
         Dq10 = Nq10/pi,
         Dq90 = Nq90/pi)

(bobo <- ggplot(b.plot) +
  geom_point(aes(x = year, y = Dmed, color = field), size = 4,
             position = position_dodge(0.5)) +
  geom_errorbar(aes(x = year, ymin = Dq2.5, ymax = Dq97.5,
                    color = field),
                width = 0,
             position = position_dodge(0.5)) +
  geom_errorbar(aes(x = year, ymin = Dq10, ymax = Dq90,
                    color = field),
                linewidth = 1,
                width = 0,
             position = position_dodge(0.5)) +
  geom_line(aes(x = year, y = Dmed, color = field),
             position = position_dodge(0.5)) +
  scale_color_manual(values = c("steelblue", "darkred")) +
  scale_x_continuous(breaks = seq(2010,2024, by = 4)) +
  ylim(0,6.1) +
  labs(y = "BOBO density (no./ha)", x = "", 
       color = "Field") +
  theme_bw() +
  theme(text = element_text(size = 13))
  )

ggsave("figures/BOBO_6years.d.field.year.int.p.year.png", height = 4, width = 6, dpi = 400)
```

# raw average counts
```{r}
# format raw count data
raw.plot <- b %>% filter(!is.na(dist)) %>% 
  group_by(field, year, pt) %>% 
  tally() %>%
  right_join(allpts %>% select(year, field, pt) %>% distinct(), 
             by = join_by(pt, year, field)) %>%
  replace_na(list(n = 0)) %>%
  arrange(pt) %>%
  mutate(dens = n/(4*3.1415)) %>% 
  group_by(field, year) %>% 
  summarize(mean.num = mean(dens),
            sd = sd(dens),
            .groups = "drop") %>%
  mutate(npts = c(rep(10,6), rep(9,6)),
         yr = c(2010, 2012, 2013, 2018, 2019, 2024, 
                2010, 2012, 2013, 2018, 2019, 2024),
         se = sd/sqrt(npts))

# plot
(raw.b <- ggplot(raw.plot) +
  geom_point(aes(x = yr, y = mean.num, color = field), size = 4,
             position = position_dodge(0.5)) +
  geom_errorbar(aes(x = yr, ymin = mean.num-(2*se), ymax = mean.num+(2*se),
                    color = field),
                width = 0,
             position = position_dodge(0.5)) +
  geom_line(aes(x = yr, y = mean.num, color = field),
             position = position_dodge(0.5)) +
  scale_color_manual(values = c("steelblue", "darkred")) +
  scale_x_continuous(breaks = seq(2010,2024, by = 4)) +
  ylim(0,2.5) +
  labs(y = "BOBO density (raw no./ha)", x = "", 
       color = "Field") +
  theme_bw() +
  theme(text = element_text(size = 13))
)

ggsave("figures/BOBO_6years.raw.field.year.png", height = 4, width = 6, dpi = 400)


```